### ISSUE TITLE
Error Failed to verify bitcode in PWLocation.framework/PWLocation After update SDK 3.8

### ISSUE THREAD

**Issue by Hadiyanto** [phunware/maas-location-ios-sdk#40]
Hi Team,

I got error when running "xcodebuild -exportArchive".

Xcode Version : 10.3
SDK Version : 3.8 

`error: exportArchive: Failed to verify bitcode in PWLocation.framework/PWLocation:
error: Linker option verification failed for bundle /var/folders/hm/z2lbnynj3lzg4drg97zv86_h0000gn/T/PWLocationNvkLTP/PWLocation.arm64.xar (unrecognized arguments: -platform_version iOS 10.0.0 13.1.0)

Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in PWLocation.framework/PWLocation:
error: Linker option verification failed for bundle /var/folders/hm/z2lbnynj3lzg4drg97zv86_h0000gn/T/PWLocationNvkLTP/PWLocation.arm64.xar (unrecognized arguments: -platform_version iOS 10.0.0 13.1.0)

" UserInfo={NSLocalizedDescription=Failed to verify bitcode in PWLocation.framework/PWLocation:
error: Linker option verification failed for bundle /var/folders/hm/z2lbnynj3lzg4drg97zv86_h0000gn/T/PWLocationNvkLTP/PWLocation.arm64.xar (unrecognized arguments: -platform_version iOS 10.0.0 13.1.0)`

Thanks

**Comment by ghost** [comment]
Hi @Hadiyanto,

Thanks for reporting this issue. I believe the latest version of our PWLocation.framework (v3.8.3) is built using Xcode 11.x.

From your logs, it looks like building with Xcode 11.x changes the way in which bitcode is generated. If true, this would mean Xcode 11+ is needed in order to verify bitcode.

Can you please try archiving using Xcode 11+ and let us know if that resolves your issue? If so, we will update our README's minimum requirements for Xcode to be 11+.

Thanks!
Troy

**Comment by Nurmarat** [comment]
Hi @tstump-phunware ,

I got other error when running using Xcode 11. I need fix it. I will inform you. you can close this issue.

Thanks.

**Comment by ghost** [comment]
Hi @Nurmarat,

This issue was opened by @Hadiyanto. Are you the same person? If so, I’ll go ahead and close this issue.

Thanks,
Troy
